Algoritmo "Concatenação"

// Descrição   : Concatenação
// Autor(a)    : Welly
// Data atual  : 15/07/2020
Var
// Seção de Declarações das variáveis 
   nome: caractere
   numero: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Digite um nome")
   leia(nome)
   escreval("Digite um numero")
   leia(numero)
   
   escreval(nome, ":" , numero, 15)

Fimalgoritmo