Algoritmo "Operadores Relacionais"

// Descrição   : Operadores Relacionais
// Autor(a)    : Welly
// Data atual  : 15/07/2020
Var
// Seção de Declarações das variáveis 
   nota1, nota2: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   nota1 := 10
   nota2 := 15
   
   se(nota1 <> nota2) entao
        escreval ("Nota 1 e diferente")
   senao
        escreval("Nota 1 e igual")
   fimse

Fimalgoritmo