Algoritmo "operadores Aritméticos"

// Descrição   : Operadores Aritméticos
// Autor(a)    : Welly
// Data atual  : 14/07/2020
Var
// Seção de Declarações das variáveis 
   resultado, valor1, valor2, valor3: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   valor1 := 10
   valor2 := 10
   valor3 := 10
   resultado := ((valor1 + valor2 + valor2) / valor3) %2
   
   escreval("Resultado: ", resultado)
   

Fimalgoritmo