Algoritmo "variáveis"
// Disciplina  :  Algoritmos 1
// Professor   : Cleison Melo
// Descrição   : Representação de Variáveis
// Autor(a)    : Welly Paixão de Araújo
// Data atual  : 25/05/2020
Var
// Seção de Declarações das variáveis 
// Primeiro Nome
// Segundo Nome
// Idade
// Cidade
// Endereço
   primeiroNome, segundoNome, cidade, endereco: caractere;
   idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo